#!/bin/bash

# settings and secrets auto generated by 2x_setup_* scripts
# rename to `setup_auto.sh`
# overwrites `secrets_default.sh`, `settings_default.sh` but not `setup_user.sh`
# scripts will only append to the end of the file, will not delete anything
# when the script is executed, only the last definition will be retained
# do not modify by hand; overwrite values by redefining them in setup_user.sh
